class CfgSurgery
{
	class Man
	{
		cost = 4999;
		faces[] = {
			{"Default","Default face"},
			{"PersianHead_A3_01","Bahadur"},
			{"PersianHead_A3_02","Jalali"},
			{"PersianHead_A3_03","Sabet"},
			{"WhiteHead_01","Bayh"},
			{"WhiteHead_02","Burr"},
			{"WhiteHead_03","Coburn"},
			{"WhiteHead_04","Collins"},
			{"WhiteHead_05","Campbell"},
			{"WhiteHead_06","Dayton"},
			{"WhiteHead_07","Dorgan"},
			{"WhiteHead_08","Halliwell"},
			{"WhiteHead_09","Johnson"},
			{"WhiteHead_10","Martinez"},
			{"WhiteHead_11","Kirby"},
			{"WhiteHead_12","Reed"},
			{"WhiteHead_13","Santorum"},
			{"WhiteHead_14","Smith"},
			{"WhiteHead_15","Snowe"},
			{"WhiteHead_16","Kelly"},
			{"WhiteHead_17","O'Connor"},
			{"WhiteHead_18","Byrne"},
			{"WhiteHead_19","O'Brien"},
			{"WhiteHead_20","Walsh"},
			{"WhiteHead_21","O'Sullivan"},
			{"AfricanHead_01","Williams"},
			{"AfricanHead_02","Hasan"},
			{"AfricanHead_03","Jesus"},
			{"GreekHead_A3_01","Athanasiadis"},
			{"GreekHead_A3_02","Baros"},
			{"GreekHead_A3_03","Constantinou"},
			{"GreekHead_A3_04","Costas"},
			{"GreekHead_A3_05","Doukas"},
			{"GreekHead_A3_06","Gikas"},
			{"GreekHead_A3_07","Christou"},
			{"GreekHead_A3_08","Kanelloupou"},
			{"GreekHead_A3_09","Savalas"},
			{"AsianHead_A3_01","Ximi"},
			{"AsianHead_A3_02","Jeong"},
			{"AsianHead_A3_03","Tung"},
			{"Nikos","{Skyline} Nikos"},
			{"Miller","{Skyline} Miller"},
			{"Kerry","{Skyline} Kerry"},
			{"kerry_B1_F","Kerry (2)"},
			{"kerry_B2_F","Kerry (3)"},
			{"Kerry_C_F","Kerry (4)"},
			{"IG_Leader","{Skyline} Leader Indep"},
			{"O_Colonel","{Skyline} Colonel OPFOR"},
			{"TanoanHead_A3_01","Simo"},
			{"asczHead_muller_A3","Muller"},
			{"asczHead_troska_A3","Troska"},
			{"asczHead_stick_A3","Stick"},
			{"asczHead_austin_A3","Austin"},
			{"asczHead_sokolov_A3","Sokolov"},
			{"asczHead_price_A3","Price"},
			{"asczHead_mctavish_A3","MacTavish"},
			{"asczHead_spanel_A3","Spanel"},
			{"asczHead_voodoo_A3","Voodoo"},
			{"asczHead_beardy_A3","Beardy"},
			{"asczHead_woods_A3","Woods"},
			{"asczHead_redfield_A3","Redfield"},
			{"asczHead_foley_A3","Foley"},
			{"asczHead_murphy_A3","Murphy"},
			{"asczHead_josephe_A3","Josephe"},
			{"asczHead_neumann_A3","Neumann"},
			{"asczHead_nevim_A3","Nevim"},
			{"asczHead_novotny_A3","Novotny"},
			{"asczHead_brown_A3","Brown"},
			{"asczHead_picleson_A3","Picleson"},
			{"asczHead_vlk_A3","Vlk"},
			{"asczHead_xong_A3","Xong"},
			{"asczHead_olson_A3","Olson"},
			{"asczHead_taurus_A3","Taurusin"},
			{"asczHead_snek_A3","Snek"},
			{"asczHead_slug_A3","Slug"},
			{"asczHead_plumber_A3","Plumber"},
			{"asczHead_hammond_A3","Hammond"},
			{"asczHead_grey_A3","Grey"},
			{"asczHead_boredslav_A3","Boredslav"},
			{"asczHead_idoka_A3","Idoka"},
			{"HITMAN_47","HITMAN 47"},
			{"TanoanHead_A3_02","Adnet"},
			{"TanoanHead_A3_03","Cahun"},
			{"TanoanHead_A3_04","Ganio"},
			{"TanoanHead_A3_05","Malet"},
			{"TanoanHead_A3_06","Solé"},
			{"TanoanHead_A3_07","Mignard"},
			{"TanoanHead_A3_08","Thibaud"},
			{"AsianHead_A3_04","Lee"},
			{"AsianHead_A3_05","Chan"},
			{"AsianHead_A3_06","Yeung"},
			{"AsianHead_A3_07","Wong"},
			{"mgsr_nakedsnake","MGSR Naked Snake"},
			{"mgsr_venomsnake","MGSR Venom Snake"},
			{"mgsr_venomsnake_demon","MGSR Venom Snake (Demon)"},
			{"mgsr_skullface","MGSR Skull Face"},
			{"GreekHead_A3_11","Gavras"},
			{"GreekHead_A3_12","Markos"},
			{"GreekHead_A3_13","Alexis"},
			{"GreekHead_A3_14","Dimitrou"},
			{"WhiteHead_23","Nathan"},
			{"Barklem","Barklem"},
			{"Mavros","Mavros"},
			{"Sturrock","Sturrock"},
			{"Ioannou","Ioannou"},
			{"RRPw_Givens_Head","RRPw_THOMAS"},
			{"WhiteHead_24","Čapek"},
			{"RRPw_Gustavo_Head","RRPw_CfgIdentities_Gustavo_FirstName"},
			{"RRPw_Said_Head","RRPw_CfgIdentities_Said_LastName"},
			{"RRPw_Journalist_Head","RRPw_CfgIdentities_Journalist_LastName"},
			{"RRPw_African_Head_Old","RRPw_WesternSahara_FirstNames9"},
			{"RRPw_African_Head_Old_Bard","RRPw_WesternSahara_FirstNames43"},
			{"RRPw_African_Head_01","RRPw_WesternSahara_FirstNames5"},
			{"RRPw_African_Head_02","RRPw_WesternSahara_FirstNames28"},
			{"RRPw_African_Head_03","RRPw_WesternSahara_FirstNames21"},
			{"RRPw_African_Head_04","RRPw_WesternSahara_FirstNames38"},
			{"RRPw_African_Head_05","RRPw_WesternSahara_FirstNames49"},
			{"WhiteHead_25","Dillon"},
			{"WhiteHead_26","Homewood"},
			{"WhiteHead_27","Kesson"},
			{"WhiteHead_28","Kingsly"},
			{"WhiteHead_29","Severov"},
			{"WhiteHead_30","Smolko"},
			{"WhiteHead_31","Stype"},
			{"WhiteHead_32","Rudwell"},
			{"LivonianHead_1","Nowak"},
			{"LivonianHead_2","Górecki"},
			{"LivonianHead_3","Kowalski"},
			{"LivonianHead_4","Stolarski"},
			{"LivonianHead_5","Burak"},
			{"LivonianHead_6","Kawa"},
			{"LivonianHead_7","Janowski"},
			{"LivonianHead_8","Sternik"},
			{"LivonianHead_9","Zieliński"},
			{"LivonianHead_10","Rabinowicz"},
			{"RussianHead_1","Ivanov"},
			{"RussianHead_2","Petrenko"},
			{"RussianHead_3","Krupin"},
			{"RussianHead_4","Adamovich"},
			{"RussianHead_5","Yakhin"},
			{"TanoanHead_A3_09","Old Man"}
		};
	};
	class Women
	{
		cost = 0;
		faces[] = {
			{"max_female1","Female1"},
			{"max_female2","Female2"},
			{"max_female3","Female3"},
			{"max_female4","Female4"},
			{"max_female5","Female5"},
			{"max_female6","Female6"},
			{"max_female7","Female7"},
			{"max_female8","Female8"},
			{"max_female9","Female9"},
			{"max_female10","Female10"},
			{"max_female11","Female11"},
			{"max_female12","Female12"},
			{"max_female13","Female13"},
			{"max_female14","Female14"},
			{"max_female15","Female15"},
			{"max_female16","Female16"},
			{"max_female17","Female17"},
			{"Fem_1","Female 1"},
			{"Fem_2","Female 2"},
			{"Fem_3","Female 3"},
			{"Fem_3B","Female 3B"},
			{"Fem_4","Female 4"},
			{"Fem_5","Female 5"},
			{"Fem_5B","Female 5B"},
			{"Fem_6","Female 6"},
			{"Fem_7","Female 7"},
			{"Fem_7_2","Female 7 2"},
			{"Fem_7B","Female 7B"},
			{"Fem_8","Female 8"},
			{"Fem_9","Female 9"},
			{"Fem_A","Female A"},
			{"Fem_A2","Female A 2"},
			{"Fem_B","Female B"},
			{"Fem_B2","Female B 2"},
			{"Fem_C","Female C"},
			{"Fem_D","Female D"},
			{"Fem_E","Female E"},
			{"Fem_F","Female F"},
			{"d3s_female1","Alina"},
			{"d3s_female2","Marlin"},
			{"d3s_female3","Alli"},
			{"TCGM_Fem_Eilish","Eilish"},
			{"TCGM_Fem_EilishBun","EilishBun"},
			{"TCGM_Fem_Fox","Fox"},
			{"TCGM_Fem_FoxBun","FoxBun"},
			{"TCGM_Fem_Lynch","Lynch"},
			{"TCGM_Fem_Stone","Stone"},
			{"TCGM_Fem_StoneBun","StoneBun"}
		};
	};
};