#include "common.hpp"
#include "shop_items.hpp"
#include "impound.hpp"
#include "bank.hpp"
#include "shops.hpp"
#include "admin_menu.hpp"
#include "Vehicle_Give.hpp"
#include "ticket.hpp"
#include "clothing.hpp"
#include "trunk.hpp"
#include "spawnSelection.hpp"
#include "chop_shop.h"
#include "vehicleShop.h"
#include "federalReserve.h"
#include "LicensesDialog.hpp"
#include "gov_bank.hpp"
#include "container.hpp"
#include "gangContainer.hpp"
#include "delivery.hpp"
#include "addwarpoint.hpp"
#include "respawnScreen.h"
#include "processmenu.hpp"
#include "freeTicket.hpp"
#include "surgery.hpp"
#include "copParking.hpp"
#include "civParking.hpp"
#include "dhl.hpp"
#include "battleVeh.hpp"
#include "copTargetMessage.hpp"
#include "placeble.hpp"
#include "place_store.hpp"
#include "call_management.hpp"
#include "changePlate.hpp"
#include "cop_db.hpp"
#include "dropcrimes.hpp"
#include "licensecontrol.hpp"
#include "reward.hpp"
#include "lottery.hpp"
#include "cas_admin.hpp"
#include "il_dialog.hpp"
#include "correctwork.hpp"
#include "EventManager.hpp"
#include "NYgifts.hpp"
#include "emptyDialog.hpp"
#include "achievments.hpp"
#include "party.hpp"
#include "groups.hpp"
#include "container_manage.hpp"
#include "bank_rob.hpp"
#include "ltd.hpp"
#include "adac.hpp"
#include "roulette.hpp"
#include "rewardsDialog.hpp"
#include "dailyReward.hpp"
#include "telegram.hpp"
#include "document.hpp"

#include "ltdReg.hpp"
#include "ltd_store.hpp"
#include "ltd_moderation.hpp"
#include "gerbs_menu.h"
#include "breakinglock.hpp"

//tablet
#include "res_capture.hpp"

#include "tablet_xp.hpp"
#include "tablet_crafting.hpp"
#include "tablet_med_status.hpp"
#include "tablet_ltdss.hpp"
#include "tablet_house_menu.h"
#include "tablet_player_inv.hpp"
#include "tablet_gov.hpp"
#include "tablet_smartphone.hpp"
#include "tablet_settings.h"
#include "tablet_health.hpp"
#include "tablet_key_chain.hpp"
#include "tablet_economy.hpp"

//documents
#include "documentsPad.hpp"
#include "documentsShop.hpp"
#include "AddDocs.hpp"
#include "showDocs.hpp"

#include "sellItems.hpp"
#include "weaponStorage.hpp"
#include "char_creation.hpp"
#include "poker_lobby.hpp"
#include "poker2.hpp"

#include "DialogVehicleSelect.hpp"
#include "party_meat.hpp"

#include "tablet.hpp"
#include "reg_group.hpp"

#include "custom_inventory.hpp"
#include "RocketDialogGiveMoney.hpp"
#include "RocketDialogJobSelection.hpp"
#include "RRPDialogChangeBet.hpp"

#include "keypad.hpp"

#include "RocketDialogAtmPinpad.hpp"
#include "RocketDialogCalibration.hpp"
#include "RocketDialogCardSwipe.hpp"
#include "RocketDialogPattern.hpp"
#include "RocketDialogSaw.hpp"

#include "give_events.hpp"