diag_log "RRPServer - start - fn_preInit";
private _headerNoDebug = '
	private _fnc_scriptNameParent = if (isNil "_fnc_scriptName") then {"%1"} else {_fnc_scriptName};
	private _fnc_scriptName = "%1";
	scriptName _fnc_scriptName;
';
private _is_dev = serverName isNotEqualTo "[RU] Aurora Role Play | rocket-rp.fun";

[
	"RRPServer_system_sendMoney",

	"RRPServer_partyMeat_gameFinish",
	"RRPServer_partyMeat_updateStats",
	"RRPServer_partyMeat_registrationPlayer",
	
	"RRPServer_playtime_cycle",

	"RRPServer_refinery_capture",
	"RRPServer_refinery_init",
	"RRPServer_refinery_produceOil",
	"RRPServer_refinery_updateAmountItems",
	"RRPServer_refinery_setFlag",

	"RRPServer_doc_addDocuments",
	"RRPServer_doc_buyDocuments",
	"RRPServer_doc_getDocuments",
	"RRPServer_doc_deleteDocument",

	"RRPServer_util_clientCompile",
	"RRPServer_headless_enableMe",
	"RRPServer_atm_bankActions",
	"RRPServer_ach_save",
	"RRPServer_DB_addBan",
	"RRPServer_util_tinyIntConverter",
	"RRPServer_DB_debug",
	"RRPServer_DB_insertRequest",
	"RRPServer_DB_log",
	"RRPServer_DB_mresString",
	"RRPServer_DB_sendRconCommand",
	"RRPServer_adac_vehicleAdacRecolor",
	"RRPServer_adac_vehicleAdacRematerial",
	"RRPServer_adac_vehicleAdacUpdate",
	"RRPServer_chopShop_chopAction",
	"RRPServer_discord_sendMessage",
	"RRPServer_event_onAnimalKilled",
	"RRPServer_event_onPlayerConnected",
	"RRPServer_event_onPlayerDisconnected",
	"RRPServer_event_player_MPKilled",
	"RRPServer_event_vehicle_MPKilled",
	"RRPServer_event_vehicleMsnHandlers",
	"RRPServer_function_v4fgsbesn45",
	"RRPServer_garage_insurancePayRequest",
	"RRPServer_garage_insurancePermanent",
	"RRPServer_garage_swapVehicle",
	"RRPServer_garage_vehicleCreate",
	"RRPServer_garage_vehicleParkingPay",
	"RRPServer_garage_vehicleParkingStore",
	"RRPServer_garbageCollector_cleanNullVehicle",
	"RRPServer_garbageCollector_GroundWeaponHolder",
	"RRPServer_garbageCollector_WeaponHolderSimulated",
	"RRPServer_house_addHouse",
	"RRPServer_house_addNeighs",
	"RRPServer_house_fetchPlayerHouses",
	"RRPServer_house_initHouses",
	"RRPServer_house_kickMeFromHouse",
	"RRPServer_house_loadHouses",
	"RRPServer_house_removeNeighs",
	"RRPServer_house_reqHouseInfo",
	"RRPServer_house_securityHouseRequest",
	"RRPServer_house_sellHouse",
	"RRPServer_house_setPayTime",
	"RRPServer_house_unlockHouseContainer",
	"RRPServer_house_updateHouseContainers",
	"RRPServer_house_updateHouseSlots",
	"RRPServer_houses_payForHouse",
	"RRPServer_inventory_save",
	"RRPServer_jail_jailSys",
	"RRPServer_jail_wantedUpdateJailTime",
	"RRPServer_lootBox_requestResult",
	"RRPServer_lottery_action",
	"RRPServer_lottery_fetchWinners2",
	"RRPServer_msg_cleanupMessages",
	"RRPServer_msg_handleMessages",
	"RRPServer_msg_msgRequest",
	"RRPServer_object_animal_animalRequest",
	"RRPServer_plates_changePlate",
	"RRPServer_police_crimesRequest",
	"RRPServer_police_dropMyCrime",
	"RRPServer_police_searchData",
	"RRPServer_skills_buyXP",
	"RRPServer_skills_saveXP",
	"RRPServer_system_HideObject",
	"RRPServer_system_RCON_Restart",
	"RRPServer_system_Rcreditslog",
	"RRPServer_system_addEventZone",
	"RRPServer_system_battleZoneSpawn",
	"RRPServer_system_changeFraction",
	"RRPServer_system_changePlayerServerMap",
	"RRPServer_system_clientDisconnect",
	"RRPServer_system_combatVehicleReq",
	"RRPServer_system_compareDigits",
	"RRPServer_system_deleteEventZone",
	"RRPServer_system_events_init",
	"RRPServer_system_federalUpdate",
	"RRPServer_system_garbageCollector",
	"RRPServer_system_getID",
	"RRPServer_system_getRandomStrings_forID",
	"RRPServer_system_huntingZone",
	"RRPServer_system_init_msnVariables",
	"RRPServer_system_keyManagement",
	"RRPServer_system_loadPlayerLoot",
	"RRPServer_system_logIt",
	"RRPServer_system_moneyChange",
	"RRPServer_system_postInit",
	"RRPServer_system_preInit",
	"RRPServer_system_prepareToRestart",
	"RRPServer_system_rcon",
	"RRPServer_system_serverCommand",
	"RRPServer_system_setPlayerSide",
	"RRPServer_system_setVarNet",
	"RRPServer_system_spikeStrip",
	"RRPServer_system_thread_addTask",
	"RRPServer_system_thread_initialize",
	"RRPServer_system_thread_removeTask",
	"RRPServer_system_thread_threadAdjust",
	"RRPServer_system_transferOwnership",
	"RRPServer_system_turtleZone",
	"RRPServer_vehicle_delete",
	"RRPServer_util_addDate",
	"RRPServer_util_debugConsole",
	"RRPServer_util_doubleDigits",
	"RRPServer_util_getRealTime",
	"RRPServer_util_safetyOwner",
	"RRPServer_util_log",
	"RRPServer_ws_wantedAdd",
	"RRPServer_ws_wantedBounty",
	"RRPServer_ws_wantedKilledbyCop",
	"RRPServer_ws_wantedPerson",
	"RRPServer_ws_wantedRemove",
	"RRPServer_system_setSideFriends",
	"RRPServer_drops_dropGifts",
	"RRPServer_drops_activateGift",
	"RRPServer_drops_posList",
	"RRPServer_weaponStorage_init"
]apply{
	_function = _x;
	_code = if (_is_dev) then {
			compile (format[_headerNoDebug,_function] + preprocessFileLineNumbers format["\RRPServer\code\%1.sqf",_function])
		} else {
			compileFinal (format[_headerNoDebug,_function] + preprocessFileLineNumbers format["\RRPServer\code\%1.sqf",_function])
		};
	missionNamespace setVariable [_function, _code];
};

call RRPServer_system_preInit;

true
